---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: wassimba
    password: takeuout2021
- name: Push to docker hub
  docker_image:
    name: cd-angular
    repository: wassimba/cd_project
    tag: latest
    source: local
    push: yes
