--- 
- 
  docker_image: 
    build: 
      path: /var/lib/jenkins/workspace/cd-angular
      pull: false
    force_source: true
    name: "cd-angular:latest"
    source: build
    state: present
  name: "create image docker"
- 
  docker_container: 
    image: "cd-angular:latest"
    name: myappcontainer
    ports: 
      - "4200:80"
    recreate: true
    state: started
  name: "run container docker"
