--- 
- 
  docker_image: 
    build: 
      path: /var/lib/jenkins/workspace/cd-angular
      pull: false
    force_source: true
    name: "cd-angular:latest"
    source: build
    state: present
  name: "create image docker"
- name: run container docker
  docker_container:
    name: myappcontainer
    image: cd-angular:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
